AllCops:
  TargetRubyVersion: 2.5.1

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Metrics/BlockLength:
  Exclude:
    - "**/*.rake"

Metrics/LineLength:
   Max: 120
